import { createApp } from "vue";
import "@fontsource/red-hat-text/400.css";
import "@fontsource/red-hat-text/500.css";
import "@fontsource/red-hat-text/600.css";
import "@fontsource/red-hat-mono/400.css";
import "@fontsource/red-hat-mono/500.css";
import "@fontsource/readex-pro/600.css";
import App from "./App.vue";
import "./style.css";
createApp(App).mount("#app");
